### ISSUE TITLE
bug: Could not append type because the JSON schema for the dictionary...is invalid (faker related?)

### ISSUE THREAD

**Issue by mjsqu** [meltano/sdk#2226] opened 2024-02-07 01:50 UTC
### Singer SDK Version

0.35.0

### Is this a regression?

- [ ] Yes

### Python Version

3.10

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Windows

### Description

The following warning messages are output before validating any tap-specific config:

https://github.com/meltano/sdk/blob/7c77366e30efff5bc04cce709ecac359fdfabc2f/singer_sdk/helpers/capabilities.py#L40
```
Could not append type because the JSON schema for the dictionary `{'oneOf': [{'type': ['number']}, {'type': ['string']}, {'type': ['boolean']}]}` appears to be invalid.

```

It appears to be due to the `typing.py` code not being able to handle appending a `null` type to an optional parameter on the newly introduced `faker_config` params in stream maps.

### Code

```Python
Property(
        "faker_config",
        ObjectType(
            Property(
                "seed",
                OneOf(NumberType, StringType, BooleanType),
                description=(
                    "Value to seed the Faker generator for deterministic output: "
                    "https://faker.readthedocs.io/en/master/#seeding-the-generator"
                ),
            ),
            Property(
                "locale",
                OneOf(StringType, ArrayType(StringType)),
                description=(
                    "One or more LCID locale strings to produce localized output for: "
                    "https://faker.readthedocs.io/en/master/#localization"
                ),
            ),
        ),
        description=(
            "Config for the [`Faker`](https://faker.readthedocs.io/en/master/) "
            "instance variable `fake` used within map expressions. Only applicable if "
            "the plugin specifies `faker` as an addtional dependency (through the "
            "`singer-sdk` `faker` extra or directly)."
        ),
    ),
```

**Comment by mjsqu** [comment] 2024-02-07 01:52
The `OneOf` type isn't happy when passed through `helpers._typing.append_type`, called from `typing.Property.to_dict`

https://github.com/meltano/sdk/blob/7c77366e30efff5bc04cce709ecac359fdfabc2f/singer_sdk/helpers/_typing.py#L52

**Comment by mjsqu** [comment] 2024-02-07 01:55
https://github.com/meltano/sdk/blob/7c77366e30efff5bc04cce709ecac359fdfabc2f/singer_sdk/helpers/capabilities.py#L40-L67

**Comment by mjsqu** [comment] 2024-02-07 01:56
Specifically the `to_dict()` in the new `faker_config` part of stream maps:

https://github.com/meltano/sdk/blob/7c77366e30efff5bc04cce709ecac359fdfabc2f/singer_sdk/helpers/capabilities.py#L40-L67

Cheers for investigating, not a huge bug, just a warning message.

**Comment by edgarrmondragon** [comment] 2024-02-07 01:56
@mjsqu thanks for reporting!

Other than the nuisance that are warning messages, is this causing any other major issues in a tap?

Related:

* https://github.com/meltano/sdk/issues/1887

**Comment by mjsqu** [comment] 2024-02-07 01:59
Oh sorry if it is a duplicate. No, just an annoyance that made me think my new tap was broken - haha

**Comment by mjsqu** [comment] 2024-02-07 02:00
Yeah, now I see that's a duplicate, apologies, should have searched a bit harder

**Comment by edgarrmondragon** [comment] 2024-02-07 02:03
> Yeah, now I see that's a duplicate, apologies, should have searched a bit harder

No worries at all 🙂

**Comment by edgarrmondragon** [comment] 2024-02-07 02:04
Closing as duplicate of #1887

**Closed by edgarrmondragon** 2024-02-07 02:04 UTC
Labels: kind/Bug, duplicate, valuestream/SDK
