### ISSUE TITLE
bug: --about `Could not append type because the JSON schema for the dictionary`

### ISSUE THREAD

**Issue by pnadolny13** [meltano/sdk#2244] opened 2024-02-15 20:32 UTC
Related to https://github.com/meltano/hub/issues/1671. This command prints the about json but it logs several warnings that it cant figure out the type. This is for one of the built in configs as part of `faker_config`.

`tap-dataverse --about --format=json`

`Could not append type because the JSON schema for the dictionary {'oneOf': [{'type': ['number']}, {'type': ['string']}, {'type': ['boolean']}]}` appears to be invalid.`

**Comment by edgarrmondragon** [comment] 2024-02-15 20:36
Closing as duplicate of https://github.com/meltano/sdk/issues/2226 😅

I guess I'll to give this 20 min to try fixing.

**Closed by edgarrmondragon** 2024-02-15 20:36 UTC

**Comment by pnadolny13** [comment] 2024-02-15 20:49
@edgarrmondragon oops I didnt find that one for some reason 😞

**Comment by edgarrmondragon** [comment] 2024-02-16 00:01
Addressed in https://github.com/meltano/sdk/releases/tag/v0.35.1
